#!/usr/bin/env bash
#
# Copyright (c) 2022 Arm Limited or its affiliates. All rights reserved.
#
# SPDX-License-Identifier: MIT

# We need to ensure that we don't run bats from the current user ${HOME} to
# avoid permission denied error, since at some point it will `cd "$OLDPWD"`
# when we already switched to ${CASSINI_TEST_ACCOUNT} via the following sudo
# command.
if ! cd /home ; then
	echo "FAIL:${TEST_SUITE_NAME}"
	exit 1
fi

if sudo -HEnu "${CASSINI_TEST_ACCOUNT}" bats "${CASSINI_TEST_BATS_OPTIONS}" "${TEST_DIR}/${TEST_SUITE_NAME}.bats"; then
	echo "PASS:${TEST_SUITE_NAME}"
	exit 0
else
	echo "FAIL:${TEST_SUITE_NAME}"
	sudo -HEns <<-'EOF'
		if [ -f "${TEST_RUNTIME_DIR}/latest-tests.log" ]; then
			echo "DEBUG:Printing the contents of the log-file:"
			cat "${TEST_RUNTIME_DIR}/latest-tests.log"
		else
			echo "DEBUG:Could not find a log-file."
		fi
		EOF
	exit 1
fi
