# Copyright (c) 2022 Arm Limited or its affiliates. All rights reserved.
#
# SPDX-License-Identifier: MIT

header:
  version: 11

repos:
  meta-arm:
    refspec: kirkstone

  meta-openembedded:
    refspec: kirkstone

  meta-virtualization:
    refspec: kirkstone

  poky:
    refspec: kirkstone
