# Copyright (c) 2022, Arm Limited.
#
# SPDX-License-Identifier: MIT

version: 2
sphinx:
  configuration: documentation/conf.py
formats:
  - pdf
python:
  install:
  - requirements: documentation/requirements.txt
