# Copyright (c) 2022 Arm Limited or its affiliates. All rights reserved.
#
# SPDX-License-Identifier: MIT

header:
  version: 10
local_conf_header:
  security: |
    DISTRO_FEATURES:append = " cassini-security"
