#!/usr/bin/env bash

SCRIPT_DIR=$(dirname "$(readlink -f "${0}")")

if bats "${SCRIPT_DIR}/oci-runtime-integration-tests.bats"; then
    echo "PASS:oci-runtime-integration-tests"
else
    echo "FAIL:oci-runtime-integration-tests"
fi
