#!/usr/bin/env bash
#
# Copyright (c) 2021-2022, Arm Limited.
#
# SPDX-License-Identifier: MIT

# We need to ensure that we don't run bats from the current user ${HOME} to
# avoid permission denied error, since at some point it will `cd "$OLDPWD"`
# when we already switched to ${EWAOL_TEST_ACCOUNT} via the following sudo
# command.
if ! cd /home ; then
    echo "FAIL:${TEST_SUITE_NAME}"
    exit 1
fi

if sudo -HEnu "${EWAOL_TEST_ACCOUNT}" bats "${TEST_DIR}/${TEST_SUITE_NAME}.bats"; then
    echo "PASS:${TEST_SUITE_NAME}"
    exit 0
else
    echo "FAIL:${TEST_SUITE_NAME}"
    exit 1
fi
