#!/usr/bin/env bash
#
# Copyright (c) 2021, Arm Limited.
#
# SPDX-License-Identifier: MIT

SCRIPT_DIR=$(dirname "$(readlink -f "${0}")")

if bats "${SCRIPT_DIR}/oci-runtime-integration-tests.bats"; then
    echo "PASS:oci-runtime-integration-tests"
else
    echo "FAIL:oci-runtime-integration-tests"
fi
